name: Generate GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: anuraghazra/github-readme-stats-action@main
        with:
          username: ${{ github.repository_owner }}
          output_folder: .github/stats
          commit_message: "chore: update github stats"
          theme: "noctis_minimus"
          title_color: "fff"
          icon_color: "8B959E"
          text_color: "9f9f9f"
          bg_color: "0E1217"
          hide_rank: false
          show_icons: true

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update stats" || echo "No changes to commit"
          git push
